### ISSUE TITLE
Visualize Survey responses

### ISSUE THREAD

**Issue by AminZeina** [yehandesilva/monkeyPoll#71]
Currently we are only showing a JSON view of a survey's responses to the survey owner. For the final milestone, we need to visualize this data, with different graphics for each type of question:

> for open-ended questions, the answers are just listed as-is, for number questions a histogram of the answers is generated, for choice questions a pie chart is generated

We will have to decide whether we want to the bulk of the work on the frontend or backend; we could either summarize the response data on the backend then give it to the frontend for display (perhaps with an endpoint for each graphic/response type's summarized data?), OR leave the current endpoint as is and generate the graphics on the frontend.

**Comment by yehandesilva** [comment]
I think we should do the response analysis on the backend. Have a seperate route in the controller that takes a survey and returns the analytics of it. Otherwise we need to do all the analysis on the frontend which adds coupling between the two. 

For examle, getting analytics of a survey would return:
- List of text responses for text questions
- Number of each input for number questions
- Number of each option for choice questions.
