### ISSUE TITLE
Update README 

### ISSUE THREAD

**Issue by MichaelKyrollos** [yehandesilva/monkeyPoll#80]
Now that there is VertexAI integrated in the project, some of the instructions for how to run the project have changed.

**Comment by yehandesilva** [comment]
@MichaelKyrollos I'm assigning you to this task since you were able the one who configured the VertexAI model in #77. The only other changes is to change the last bit of the README to highlight what was achieved in this milestone and getting rid of our plans for the next milestone since this is our last one.
